out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: ZINC-MLPe
  group: Spasm+RWSE
  entity: YOUR_ENTITY_HERE
dataset:
  format: PyG-ZINC-Spasm
  name: subset
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: TypeDictNode+NodeCountEnc+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 16
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 42
  dim_hid: 28
  dim_ct: 16
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
  enforce_param_budget: true
  param_budget: 500000
model:
  type: MLPeGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 2
  dim_hidden: 64
  residual_connection: True
  batch_norm: True
  dropout: 0.1
  head:
    type: san_graph
    hidden_layers: 2
  edge_encoder:
    layers: 8
    dim_hidden: 128
    residual_connection: True
    batch_norm: True
    dropout: 0.1
  graph_encoder:
    layers: 4
    dim_hidden: 192
    residual_connection: True
    batch_norm: True
    dropout: 0.1
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 1200
  scheduler: custom_cosine_with_warmup #orginally cosine_with_warmup
  num_warmup_epochs: 10
