out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: synth-MLP
  group: synth-MLP-lapPE
  entity: YOUR_ENTITY_HERE
dataset:
  format: EmJ-Synth
  name: FracDom
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: TypeDictNode+LapPE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 63
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 4
  dim_hidden: 128
  residual_connection: True
  batch_norm: True
  dropout: 0.2
  head: san_graph
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 0.0
  reduce_factor: 0.5
  schedule_patience: 10
  base_lr: 0.001
  max_epoch: 1000
  scheduler: StepLR_with_warmup
  num_warmup_epochs: 0