out_dir: results
metric_best: ap
wandb:
  use: True
  project: Peptides-Func
  group: MoSE-omega
  entity: YOUR_ENTITY_HERE
dataset:
  format: OGB
  name: peptides-functional-all5
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  # node_encoder_name: Atom+LapPE
  node_encoder_name: Atom+NodeCountEnc
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 31
  dim_hid: 31
  dim_ct: 31
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: None+Transformer
  layers: 4
  n_heads: 4
  dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.00001
  base_lr: 0.0003
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10